### ISSUE TITLE
Any plans to pack this?

### ISSUE THREAD

**Issue by uhlhosting** [sabbir360/mattermost-sentry#1]
Can this be installed with pip directly into sentry docker?

**Comment by sabbir360** [comment]
Currently its not possible, but as its open for all to modify as required, you can do it. 
Also, note that: This script runs as a hook, so its need a port to be opened to work, if its install-able yet you need to expose that port in docker. 
The workaround could be: 
1.  Created your own Dockerfile
2.  Add sentry stuff
3. Clone this repo
4. Add command to run this script and sentry 
5. Expose all required port
